# Generated by Django 2.2.7 on 2020-02-25 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vezeeta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicianpatientbooking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='physicianpatientbooking',
            name='updated_at',
        ),
    ]
