# Generated by Django 2.2.7 on 2020-02-25 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vezeeta', '0002_auto_20200225_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicianpatientbooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physicianpatientbooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
