# Generated by Django 2.2.7 on 2020-02-25 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vezeeta', '0005_auto_20200225_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicpatientbooking',
            name='booking_date_clinic',
        ),
        migrations.RemoveField(
            model_name='physicianpatientbooking',
            name='booking_date_clinic',
        ),
        migrations.RemoveField(
            model_name='physicianpatientbooking',
            name='booking_date_hospital',
        ),
    ]
