# Generated by Django 2.2.7 on 2020-02-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vezeeta', '0007_auto_20200225_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicpatientbooking',
            name='booking_date_clinic',
        ),
        migrations.RemoveField(
            model_name='clinicpatientbooking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='clinicpatientbooking',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='hospitalpatientbooking',
            name='booking_date_hospital',
        ),
        migrations.RemoveField(
            model_name='hospitalpatientbooking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hospitalpatientbooking',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='physicianpatientbooking',
            name='booking_date_clinic',
        ),
        migrations.RemoveField(
            model_name='physicianpatientbooking',
            name='booking_date_hospital',
        ),
        migrations.RemoveField(
            model_name='physicianpatientbooking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='physicianpatientbooking',
            name='updated_at',
        ),
    ]
