# Generated by Django 2.2.7 on 2020-02-25 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vezeeta', '0008_auto_20200225_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicpatientbooking',
            name='booking_date_clinic',
            field=models.DateTimeField(blank=True, db_column='Booking_Date_clinic', null=True),
        ),
        migrations.AddField(
            model_name='clinicpatientbooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinicpatientbooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hospitalpatientbooking',
            name='booking_date_hospital',
            field=models.DateTimeField(blank=True, db_column='Booking_Date_Hospital', null=True),
        ),
        migrations.AddField(
            model_name='hospitalpatientbooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitalpatientbooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='physicianpatientbooking',
            name='booking_date_clinic',
            field=models.DateTimeField(blank=True, db_column='Booking_Date_clinic', null=True),
        ),
        migrations.AddField(
            model_name='physicianpatientbooking',
            name='booking_date_hospital',
            field=models.DateTimeField(blank=True, db_column='Booking_Date_Hospital', null=True),
        ),
        migrations.AddField(
            model_name='physicianpatientbooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physicianpatientbooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
