# Generated by Django 2.2.7 on 2020-02-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vezeeta', '0009_auto_20200225_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicpatientbooking',
            name='booking_date_clinic',
            field=models.DateField(blank=True, db_column='Booking_Date_clinic', null=True),
        ),
        migrations.AlterField(
            model_name='hospitalpatientbooking',
            name='booking_date_hospital',
            field=models.DateField(blank=True, db_column='Booking_Date_Hospital', null=True),
        ),
        migrations.AlterField(
            model_name='physicianpatientbooking',
            name='booking_date_clinic',
            field=models.DateField(blank=True, db_column='Booking_Date_clinic', null=True),
        ),
        migrations.AlterField(
            model_name='physicianpatientbooking',
            name='booking_date_hospital',
            field=models.DateField(blank=True, db_column='Booking_Date_Hospital', null=True),
        ),
    ]
