# Generated by Django 2.2.7 on 2020-02-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0008_auto_20200225_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalinstitutions',
            name='about',
            field=models.TextField(blank=True, db_column='About', null=True),
        ),
        migrations.AddField(
            model_name='medicalinstitutions',
            name='standard_fee',
            field=models.TextField(blank=True, db_column='Standard_Fee', null=True),
        ),
    ]
